export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

export const POSTS_WAITING = "POSTS_WAITING";
export const POSTS_READY = "POSTS_READY";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const USERS_WAITING = "USERS_WAITING";
export const USERS_READY = "USERS_READY";

export const FETCH_PROPERTIES_REQUEST = "FETCH_PROPERTIES_REQUEST";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
export const FETCH_PROPERTIES_FAILED = "FETCH_PROPERTIES_FAILED";

export const PROPERTIES_WAITING = "PROPERTIES_WAITING";
export const PROPERTIES_READY = "PROPERTIES_READY";
